import type { Metadata } from "next";
import SideBar from "@/components/SideBar";
import QueryProvider from "@/providers/QueryProvider";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-normal text-s flex flex-row gap-spacing-10 w-full">
        <QueryProvider>
          {children}
          <SideBar />
        </QueryProvider>
      </body>
    </html>
  );
}
