import type { Metadata } from "next";
import {
  QueryClient,
  dehydrate,
  HydrationBoundary,
} from "@tanstack/react-query";
import SideBar from "@/components/SideBar/SideBar";
import QueryProvider from "@/query/QueryProvider";
import { categoriesQueries, tagsQueries } from "@/query";
import { AppStateProvider } from "@/context/AppStateContext";
import { QUERY_CLIENT_DEFAULT_OPTIONS } from "@/lib";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient({
    defaultOptions: QUERY_CLIENT_DEFAULT_OPTIONS,
  });

  // 카테고리와 태그 데이터를 미리 패칭하여 초기 상태로 제공
  await Promise.all([
    queryClient.prefetchQuery(categoriesQueries.all()),
    queryClient.prefetchQuery(tagsQueries.all()),
  ]);

  return (
    <html lang="en">
      <body className="antialiased font-normal text-s flex flex-row gap-spacing-10 w-full">
        <AppStateProvider>
          <QueryProvider>
            <HydrationBoundary state={dehydrate(queryClient)}>
              {children}
              <SideBar />
            </HydrationBoundary>
          </QueryProvider>
        </AppStateProvider>
      </body>
    </html>
  );
}
